CHAINENV_PIP_REHASH_ROOT="${BASH_SOURCE[0]%/*}/pip-rehash"
CHAINENV_REHASH_COMMAND="${CHAINENV_COMMAND##*/}"

# Remove any version information, from e.g. "pip2" or "pip3.4".
if [[ $CHAINENV_REHASH_COMMAND =~ ^(pip|easy_install)[23](\.\d)?$ ]]; then
  CHAINENV_REHASH_COMMAND="${BASH_REMATCH[1]}"
fi

if [ -x "${CHAINENV_PIP_REHASH_ROOT}/${CHAINENV_REHASH_COMMAND}" ]; then
  CHAINENV_COMMAND_PATH="${CHAINENV_PIP_REHASH_ROOT}/${CHAINENV_REHASH_COMMAND##*/}"
  CHAINENV_BIN_PATH="${CHAINENV_PIP_REHASH_ROOT}"
  export CHAINENV_REHASH_REAL_COMMAND="${CHAINENV_COMMAND##*/}"
fi
