#!/usr/bin/env bash
# Summary: Show the current Python version(s) and its origin
#
# Shows the currently selected Python version(s) and how it was
# selected. To obtain only the version string, use `chainenv
# version-name'.

set -e
[ -n "$CHAINENV_DEBUG" ] && set -x

exitcode=0
OLDIFS="$IFS"
IFS=: CHAINENV_VERSION_NAMES=($(chainenv-version-name)) || exitcode=$?
IFS="$OLDIFS"

for CHAINENV_VERSION_NAME in "${CHAINENV_VERSION_NAMES[@]}"; do
  echo "$CHAINENV_VERSION_NAME (set by $(chainenv-version-origin))"
done

exit $exitcode
