#!/usr/bin/env bash
# Summary: Display the root directory for chainenv
#
# Usage: chainenv root [--config]
#
#   --config         Show the root directory for user configuration (shims, version)
#
if [ "$1" = "--config" ]; then
  echo "$CHAINENV_CONFIG_ROOT"
else
  echo "$CHAINENV_ROOT"
fi
