#!/usr/bin/env bash
# Usage: chainenv completions <command> [arg1 arg2...]

set -e
[ -n "$CHAINENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  chainenv-help --usage completions >&2
  exit 1
fi

# Provide chainenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec chainenv-commands
fi

COMMAND_PATH="$(command -v "chainenv-$COMMAND" || command -v "chainenv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide chainenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
