#!/usr/bin/env bash
# Summary: List all Python versions that contain the given executable
# Usage: chainenv whence [--path] <command>

set -e
[ -n "$CHAINENV_DEBUG" ] && set -x

# Provide chainenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec chainenv-shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  chainenv-versions --bare | while read -r version; do
    path="$(chainenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

CHAINENV_COMMAND="$1"
if [ -z "$CHAINENV_COMMAND" ]; then
  chainenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$CHAINENV_COMMAND")"
[ -n "$result" ] && echo "$result"
