#!/usr/bin/env bash
# Usage: chainenv version-file [<dir>]
# Summary: Detect the file that sets the current chainenv version
set -e
[ -n "$CHAINENV_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -f "${root}/.chainenv-version" ]; then
      echo "${root}/.chainenv-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$CHAINENV_DIR" || {
    [ "$CHAINENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || echo "${CHAINENV_CONFIG_ROOT}/version"
fi
