#!/usr/bin/env bash
set -e
[ -n "$CHAINENV_DEBUG" ] && set -x

# Provide chainenv completions
if [ "$1" = "--complete" ]; then
  exec chainenv-rehash --complete
fi

shell="$(basename "${CHAINENV_SHELL:-$SHELL}")"

# When chainenv shell integration is enabled, delegate to chainenv-rehash,
# then tell the shell to empty its command lookup cache.
chainenv-rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
