#!/usr/bin/env bash
# Usage: chainenv version-file-write <file> <version>

set -e
[ -n "$CHAINENV_DEBUG" ] && set -x

CHAINENV_VERSION_FILE="$1"
shift || true
versions=("$@")

if [ -z "$versions" ] || [ -z "$CHAINENV_VERSION_FILE" ]; then
  chainenv-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
chainenv-prefix "${versions[@]}" >/dev/null

# Write the version out to disk.
# Create an empty file. Using "rm" might cause a permission error.
> "$CHAINENV_VERSION_FILE"
for version in "${versions[@]}"; do
  echo "$version" >> "$CHAINENV_VERSION_FILE"
done
